

dubbo:
  zookeeper:
    #    address: zookeeper://172.30.66.104:2181
    address: zookeeper://localhost:2181
  group: group-one
  timeout: 5000
  version: localhost
  port: 30000
  retries: 0
server:
  port: 8080
